// CPU core using OpcodesFull metadata when available
const FLAG_C = 0x01; const FLAG_Z = 0x02; const FLAG_I = 0x04; const FLAG_D = 0x08; const FLAG_X = 0x10; const FLAG_M = 0x20; const FLAG_V = 0x40; const FLAG_N = 0x80;

class CPU65C816 {
  constructor(memory) {
    this.mem = memory;
    this.A = 0;
    this.X = 0;
    this.Y = 0;
    this.SP = 0x01FF;
    this.D = 0x0000;
    this.DB = 0x00;
    this.PB = 0x00;
    this.P = 0x34;
    this.PC = 0x0000;
    this.cycles = 0;
    this.running = false;
    this.pendingNMI = false;
    this.pendingIRQ = false;
    this.vblank = false;
  }

  reset() {
    const lo = this.mem.read8(0x0000);
    const hi = this.mem.read8(0x0001);
    this.PC = (hi<<8)|lo;
    this.cycles = 7;
  }

  push8(val) { const addr = (this.SP & 0xFFFF); this.mem.write8(addr, val & 0xFF); this.SP = (this.SP - 1) & 0xFFFF; }
  push16(val) { this.push8((val>>>8)&0xFF); this.push8(val&0xFF); }
  pull8() { this.SP = (this.SP + 1) & 0xFFFF; const addr = (this.SP & 0xFFFF); return this.mem.read8(addr); }
  pull16() { const lo = this.pull8(); const hi = this.pull8(); return lo | (hi<<8); }

  fetch8() { const addr = (this.PB << 16) | (this.PC & 0xFFFF); const v = this.mem.read8(addr); this.PC = (this.PC + 1) & 0xFFFF; return v; }
  fetch16() { const lo = this.fetch8(); const hi = this.fetch8(); return lo | (hi<<8); }

  // helper to sanitize handler names from meta
  _handlerNameFromMeta(meta) {
    if (!meta) return null;
    const mnemonic = meta.mnemonic || 'OP';
    const mode = meta.mode || 'impl';
    const name = `op_${mnemonic}_${mode}`.replace(/[^A-Za-z0-9_]/g,'');
    return name;
  }

  step() {
    // Service interrupt flags at instruction boundary
    if (this.pendingNMI) { this._enterNMI(); this.pendingNMI = false; }
    if (this.pendingIRQ && !(this.P & FLAG_I)) { this._enterIRQ(); this.pendingIRQ = false; }

    const startCycles = this.cycles;

    const opcode = this.fetch8();

    // Prefer the comprehensive OpcodesFull metadata if available
    let meta = null;
    if (window.OpcodesFull && window.OpcodesFull[opcode]) meta = window.OpcodesFull[opcode];
    let handlerName = null;
    let baseCycles = null;

    if (meta) {
      handlerName = this._handlerNameFromMeta(meta);
      baseCycles = meta.cycles || meta.bytes || 0; // meta.cycles should exist; fallback to bytes
    } else if (window.Opcodes && window.Opcodes.lookup) {
      const entry = window.Opcodes.lookup(opcode);
      if (entry) {
        handlerName = entry.handler;
        baseCycles = entry.cycles;
      }
    }

    if (!handlerName) {
      console.log(`Unhandled opcode 0x${opcode.toString(16)} at PB=0x${this.PB.toString(16)} PC=0x${(this.PC-1).toString(16)}`);
      this.running = false;
      return 0;
    }

    // Execute handler if implemented
    if (typeof this[handlerName] === 'function') {
      try {
        this[handlerName]();
      } catch (e) {
        console.error(`Error in handler ${handlerName}:`, e);
        this.running = false;
      }
    } else {
      // Try alternate naming patterns (mnemonic-only handlers)
      const mn = meta && meta.mnemonic ? `op_${meta.mnemonic}` : null;
      if (mn && typeof this[mn] === 'function') {
        this[mn]();
      } else {
        // If the specific handler wasn't found, also try impl-suffixed name as fallback
        const implName = meta ? (`op_${meta.mnemonic || 'OP'}_impl`) : null;
        if (implName && typeof this[implName] === 'function') {
          this[implName]();
        } else {
          console.warn(`Opcode handler ${handlerName} not implemented`);
          this.running = false;
        }
      }
    }

    // Apply base cycles if known, otherwise fall back to 1
    if (typeof baseCycles === 'number') this.cycles += baseCycles; else this.cycles += 1;

    // Return cycles consumed for this instruction (so emulator can advance PPU accurately)
    const consumed = this.cycles - startCycles;
    return consumed;
  }

  _enterNMI() {
    const pc = this.PC & 0xFFFF;
    this.push16(pc);
    this.push8(this.P);
    const lo = this.mem.read8(0xFFFA);
    const hi = this.mem.read8(0xFFFB);
    this.PC = (hi<<8)|lo;
    this.P &= ~FLAG_D;
    this.P |= FLAG_I;
  }

  _enterIRQ() {
    const pc = this.PC & 0xFFFF;
    this.push16(pc);
    this.push8(this.P);
    const lo = this.mem.read8(0xFFFE);
    const hi = this.mem.read8(0xFFFF);
    this.PC = (hi<<8)|lo;
    this.P |= FLAG_I;
  }

  // Minimal set of opcode handlers remain (handlers generated by opcodes_loader will augment prototype)
  op_NOP_impl() {}
  op_BRK_impl() { this.running = false; }
  op_BRK() {
    // Implement BRK behavior: push PC (current), push P with B flag set, set I flag, vector to IRQ/BRK vector at 0xFFFE
    try {
      const pc = this.PC & 0xFFFF; // PC already points to next instruction after opcode fetch
      this.push16(pc);
      // set B flag in pushed status (bit 4)
      this.push8(this.P | 0x10);
      // disable interrupts
      this.P |= FLAG_I;
      const lo = this.mem.read8(0xFFFE);
      const hi = this.mem.read8(0xFFFF);
      this.PC = (hi<<8)|lo;
    } catch (e) {
      console.error('BRK handler error', e);
      this.running = false;
    }
  }
  op_RTI_impl() { this.P = this.pull8(); this.PC = this.pull16(); }
  op_RTS_impl() { const ret = this.pull16(); this.PC = (ret + 1) & 0xFFFF; }

  // Fallback handlers for common mnemonics (the loader will add more specific ones)
  op_LDA_imm() { const is8 = (this.P & FLAG_M)!==0; if (is8) { this.A = this.fetch8() & 0xFF; this._setZN8(this.A); } else { this.A = this.fetch16() & 0xFFFF; this._setZN16(this.A); } }
  op_STA_abs() { const addr = window.Addressing.abs(this); const is8 = (this.P & FLAG_M)!==0; if (is8) this.mem.write8(addr, this.A & 0xFF); else this.mem.write16(addr, this.A & 0xFFFF); }

  _setZN8(v) { if ((v & 0x80)!==0) this.P |= FLAG_N; else this.P &= ~FLAG_N; if ((v & 0xFF)===0) this.P |= FLAG_Z; else this.P &= ~FLAG_Z; }
  _setZN16(v) { if ((v & 0x8000)!==0) this.P |= FLAG_N; else this.P &= ~FLAG_N; if ((v & 0xFFFF)===0) this.P |= FLAG_Z; else this.P &= ~FLAG_Z; }
}

window.CPU65C816 = CPU65C816;
